"""全局常量配置。"""

# 集市配置
DEFAULT_MARKET_STOCK_INCREASE = 10
KAPPA = {
    "comsumable": 0.11,
    "valuable": 0.11,
}
SIGMA = {
    "comsumable": 0.15,
    "valuable": 0.4,
}

# 模型配置
ACT_MODEL_NAME = "gpt-4.1-mini-2025-04-14"
PLAN_MODEL_NAME = "gpt-5-mini-2025-08-07"
REFLECT_MODEL_NAME = "gpt-5-mini-2025-08-07"

# 角色属性配置
HUNGER_DECAY_PER_DAY = 8
THIRST_DECAY_PER_DAY = 10
FATIGUE_DECAY_PER_DAY = -20
FATIGUE_DECAY_PER_ACTION = 5
ATTR_CN_MAP = {
    "hunger": "饱食度",
    "thirst": "水分值",
    "fatigue": "精神值",
}

# 游戏机制配置
WIN_CONDITION = 10000
RANDOM_EVENT_PORB = 0.1

# 运行主循环配置
USE_ACION_LAYER = False
TICK_INTERVAL_SECONDS = 1.0
ACTION_LAYER_CONNECT_POLL_SECONDS = 1.0

"""运行时参数配置。"""

# 动作重试与重规划
MAX_ACTION_RETRIES = 2
MAX_REPLAN_AFTER_ACTION_ERROR = 2

# 行为保护阈值
REPEAT_ACTION_GUARD_THRESHOLD = 2
REPEAT_TRADE_SAME_ITEM_THRESHOLD = 3
ALLOW_OPPOSITE_TRADE_SAME_ITEM_SAME_DAY = False

# 反思触发间隔
REFLECT_MIN_INTERVAL_STEPS = 20

# 生存危险阈值
SURVIVAL_HUNGER_THRESHOLD = 20.0
SURVIVAL_THIRST_THRESHOLD = 20.0
SURVIVAL_FATIGUE_THRESHOLD = 15.0
